parameters:
  - name: SNYK_TOKEN # name of the parameter; required
    type: string # data type of the parameter; required
  - name: IMAGE_NAME
    default: apache
  - name: DOCKERFILE_PATH
    default: .

jobs:
  - job: Snyk
    steps:
      - task: CmdLine@2
        displayName: "Install Snyc CLI"
        inputs:
          script: |
            curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
            chmod +x ./snyk
            mv ./snyk /usr/local/bin/
      - task: CmdLine@2
        displayName: "Build docker image"
        inputs:
          script: |
            docker build -t ${{ parameters.IMAGE_NAME }} ${{ parameters.DOCKERFILE_PATH }}
      - task: CmdLine@2
        displayName: "Scan Docker files"
        inputs:
          script: |
            snyk container test ${{ parameters.IMAGE_NAME }} --sarif
            snyk container test ${{ parameters.IMAGE_NAME }} --sarif > $(Build.ArtifactStagingDirectory)/snyk-iac.sarif || true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/snyk-iac.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"
